services:
  mysql:
    image: vinilope/cwdb:samuel
    container_name: container_sql_local
    restart: always
    ports:
      - "3307:3306"

  jar:
    image: samueuoliveira/jar:1.0
    container_name: jar_local
    hostname: desktop_004
    restart: always
    depends_on:
      - mysql
