services:
  mysql:
    image: vinilope/cwdb:1.5
    container_name: container_sql_local
    restart: always
    ports:
      - "3307:3306"

  jar:
    image: vinilope/jar:1.0
    container_name: jar_local
    restart: always
    hostname: DESKTOP_001
    depends_on:
      - mysql

volumes:
  mysql_data: 