services:
  mysql:
    image: centerwatch/bd_local_jar:1.0
    container_name: container_sql_local
    restart: always
    ports:
      - "3307:3306"

  jar:
    image: lucasfaes/jar:1.0
    container_name: jar_local
    restart: always
    hostname: container_faes
    depends_on:
      - mysql
